# Generated by Django 5.1 on 2024-11-16 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ibge', models.CharField(max_length=7, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capital', models.BooleanField(default=False)),
                ('codigo_uf', models.IntegerField()),
                ('siafi_id', models.IntegerField()),
                ('ddd', models.CharField(max_length=2)),
                ('fuso_horario', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=100, unique=True)),
                ('titulo', models.TextField()),
                ('subtitulo', models.TextField()),
                ('fonte', models.TextField()),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.CreateModel(
            name='MacroRegiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Macro Região',
                'verbose_name_plural': 'Macro Regiões',
            },
        ),
        migrations.CreateModel(
            name='RegiaoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('macro_regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.macroregiao')),
            ],
            options={
                'verbose_name': 'Região de Saúde',
                'verbose_name_plural': 'Regiões de Saúde',
            },
        ),
        migrations.CreateModel(
            name='ValorIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('valor', models.FloatField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cidade')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.indicador')),
                ('regiao_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.regiaosaude')),
            ],
            options={
                'verbose_name': 'Valor do Indicador',
                'verbose_name_plural': 'Valores dos Indicadores',
                'unique_together': {('cidade', 'indicador', 'ano')},
            },
        ),
    ]
