# Generated by Django 5.1 on 2024-11-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('fonte', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(max_length=255)),
            ],
        ),
    ]
