# Generated by Django 5.1 on 2024-11-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='ano_2010',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ano_2011',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ano_2012',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ano_2013',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ano_2014',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ano_2015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ano_2016',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ano_2017',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ano_2018',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ano_2019',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ano_2020',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='codigo_ibge',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
