# Generated by Django 5.1 on 2024-11-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_indicator_ano_2010_indicator_ano_2011_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='ano_2010',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='ano_2011',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='ano_2012',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='ano_2013',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='ano_2014',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='ano_2015',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='ano_2016',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='ano_2017',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='ano_2018',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='ano_2019',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='ano_2020',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='codigo_ibge',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='municipio',
        ),
    ]
