# Generated by Django 5.1 on 2024-11-16 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_indicator_ano_2010_remove_indicator_ano_2011_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indicator',
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='indicador',
            options={},
        ),
        migrations.AlterModelOptions(
            name='macroregiao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='regiaosaude',
            options={},
        ),
        migrations.AlterModelOptions(
            name='valorindicador',
            options={},
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='codigo_uf',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='ddd',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='fuso_horario',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='siafi_id',
        ),
        migrations.RemoveField(
            model_name='valorindicador',
            name='regiao_saude',
        ),
        migrations.AddField(
            model_name='cidade',
            name='regiao_saude',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.regiaosaude'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='subtitulo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valorindicador',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
