# Generated by Django 5.1 on 2024-11-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_estabelecimento_tipounidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='codigo_atividade_ensino_unidade',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='codigo_esfera_administrativa_unidade',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='codigo_estabelecimento_saude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='codigo_identificador_turno_atendimento',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='codigo_motivo_desabilitacao_estabelecimento',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='codigo_municipio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='codigo_natureza_organizacao_unidade',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='codigo_nivel_hierarquia_unidade',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='codigo_tipo_unidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='codigo_uf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='descricao_esfera_administrativa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='descricao_natureza_juridica_estabelecimento',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='descricao_nivel_hierarquia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='endereco_email_estabelecimento',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='estabelecimento_possui_atendimento_hospitalar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='estabelecimento_possui_centro_neonatal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='estabelecimento_possui_centro_obstetrico',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='natureza_organizacao_entidade',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='nome_razao_social',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='numero_cnpj',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='numero_cnpj_entidade',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='tipo_gestao',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
